### ISSUE TITLE
After using ErrDoc , I have met several problems.

### ISSUE THREAD

**Issue by lc3412** [yuchi1989/ErrDoc#2]
hi 
After using ErrDoc , I have met several problems.
1. In the  ErrDoc/EP/error_spec.txt , function foo error specification is  [ foo, -1, -1, EQ, -1, -1, I ].  In theory,  in the non-error path of function foo  which is in the  ErrDoc/EP/example.c, the return value can be assigned any Integer  except -1.However, ErrDoc can't detect any bugs if I change return 0 into return 1.   
2. ErrDoc seems fail to find EC bug about function fgets in my own test suite.
void CWE252_Unchecked_Return_Value__char_fgets_01_bad()
{
    {
        /* By initializing dataBuffer, we ensure this will not be the
         * CWE 690 (Unchecked Return Value To NULL Pointer) flaw for fgets() and other variants */
        char dataBuffer[100] = "";
        char * data = dataBuffer;
        printLine("Please enter a string: ");
        /* FLAW: Do not check the return value */
        fgets(data, 100, stdin);
        printLine(data);
    }
}
3. If convenient, would you mind upload the analysis data which is used in your paper ? 
4. I also don't understand what's the  meaning of ErrDoc/EP/target_spec.txt?

**Comment by yuchi1989** [comment]
@lc3412 Hi, thank you for your comments. I have updated the code. In the previous version, the checker only uses the default global return error specification even though there is a foo specification in the error specification. The updated version solves the issue you mentioned. Please let me know if you have any question. I also makes the error_spec.txt and target_spec.txt consistent. 
(The updated code of ErrDocEP.cpp is from line 830 to line 845.)

In your example, the caller returns void, so there is no propagation. If the caller has no return, then the definition of error propagation bug will be different. If you define the error handling bug from AST level for your case, you can use a AST matcher to check. But this part is out of the scope of the ErrDocEP.cpp.

**Comment by lc3412** [comment]
Thanks for your reply. I also want to ask you another question. What's the meaning of RETURN_VAL, -1, 0, NE, -1, -1, I in ErrDoc/EP/error_spec.txt ?

**Comment by yuchi1989** [comment]
RETURN_VAL means the global error specification. RETURN_VAL, -1, 0, NE, -1, -1 means that for all the functions not explicitly listed in error_spec.txt or target_spec.txt, returning non-zero value means returning error and returning 0 means returning non-error.

For many software or libraries, they have some convention of error return value. The RETURN_VAL specification makes writing error specification very convenient.
